service: dotnettwitterbot

provider:
  name: aws
  runtime: dotnetcore2.1
environment:
  TWITTER_API_KEY: ${env:TWITTER_API_KEY}
  TWITTER_API_SECRET: ${env:TWITTER_API_SECRET}
  TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
  TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
  AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

package:
  individually: true

functions:
  hello:
    handler: CsharpHandlers::DailyWholesome.Handler::Hello
    package:
      artifact: bin/release/hello.zip
    events:
      - schedule: rate(4 hours)
      - sns: trigger-tweet
  likes:
    handler: CsharpHandlers::DailyWholesome.Handler::Likes
    package:
      artifact: bin/release/likes.zip
    events:
      - schedule: rate(60 minutes)
      - sns: trigger-tweet-likes
  news:
    handler: CsharpHandlers::DailyWholesome.Handler::News
    package:
      artifact: bin/release/news.zip
    events:
      - schedule: rate(5 hours)
      - sns: trigger-tweet
